services:
  homie_llm:
    devices:
      - "nvidia.com/gpu=all"
  homie_stt:
    image: ghcr.io/ggml-org/whisper.cpp:main-cuda
    devices:
      - "nvidia.com/gpu=all"
  homie_tts:
    devices:
      - "nvidia.com/gpu=all"
