services:
  homie_ollama:
    image: ollama/ollama
    container_name: homie_ollama
    volumes:
      - ollama:/root/.ollama
    networks:
      - homie_net
    stdin_open: true
    tty: true
    restart: unless-stopped
  homie_whisper:
    image: ghcr.io/ggml-org/whisper.cpp:main
    container_name: homie_whisper
    command: ["whisper-server --host 0.0.0.0 -m /models/${STT_MODEL:?STT_MODEL is not set. Please define it in your .env file or environment}"]
    volumes:
      - ${PROJECT_PATH:?PROJECT_PATH is not set. Please define it in your .env file or environment}/models:/models
    networks:
      - homie_net
    stdin_open: true
    tty: true
    restart: unless-stopped
  homie_tts:
    image: homie_tts
    container_name: homie_tts
    volumes:
      - ${PROJECT_PATH:?PROJECT_PATH is not set. Please define it in your .env file or environment}/tts/hf-cache:/cache/huggingface
      - ${PROJECT_PATH:?PROJECT_PATH is not set. Please define it in your .env file or environment}/tts/audio_output:/audio
    networks:
      - homie_net
    stdin_open: true
    tty: true
    restart: unless-stopped
  homie_main:
    image: homie_main
    container_name: homie_main
    ports:
      - "5000:5000"
    networks:
      - homie_net
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  ollama:

networks:
  homie_net:
    external: true

